server:  
  port: 9191
  
spring:
   application:
      name: API-GATEWAY  
   zipkin:
      base-url: http://localhost:9411
      
   cloud:
      gateway:
        routes:
         - id: AUTH-SERVICE
           uri: lb://AUTH-SERVICE
           predicates:
             - Path=/olx/user/**
         - id: ADVERTISE-SERVICE
           uri: lb://ADVERTISE-SERVICE
           predicates:
             - Path=/olx/advertise/**
         - id: MASTERDATA-SERVICE
           uri: lb://MASTERDATA-SERVICE
           predicates:
             - Path=/olx/masterdata/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 