server:
   port: 9000
   
spring:
   datasource:   
      url: jdbc:mysql://localhost:3306/olx-users
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
   jpa:
      generate-ddl: true
      show-sql: true
      
      hibernate.ddl-auto: update
      properties:
          hibernate:
             dialect:org.hibernate.dialect.MySQL8Dialect
             


   application:      name: auth-service

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true

     
  
  
    
