server:
  port: 8888
  
  
spring:  application:    name: configuration-server
    
  cloud:    config:      server:        git:          uri: https://github.com/sakshikapse/olx-config
          default-label: main
          username: sakshikapse
          password: xx
          clone-on-start: true
