server:
   port: 9001
   

spring:             
   application:    name: masterdata-service
  
   zipkin:
      base-url: http://localhost:9411   
      
   config:
      import: configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true