server:
   port: 9002

spring:
   datasource:   
      url: jdbc:mysql://localhost:3306/olx-advertises
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
   jpa:
      hibernate.ddl-auto: none
      properties:
          hibernate:
             dialect:org.hibernate.dialect.MySQL8Dialect
             
   application:
    name: advertise-service
    
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true         
             
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      
#      base-path: /olx-monitor
#  
#      endpoint:
#       shutdown:
#        enabled: true
#  
#      health:
#        enabled:  true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"  
      base-path: /olx-advertise-monitor
  health:    
     circuitbreakers:     
       enabled: true
  endpoint:   
     health:      
       show-details: always
      
      
resilience4j:
  circuitbreaker:
    instances:
      STATUS-FROM-MASTER-DATA-SERVICE:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s 
      TOKEN-VALIDATION-SERVICE:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s 
        
     